name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
      - test
      - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Define Docker tags
        id: vars
        run: |
          if [[ "$BRANCH_NAME" == "dev" ]]; then
            echo "TAGS=ndeepak0x/customkali:dev" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "test" ]]; then
            echo "TAGS=ndeepak0x/customkali:test" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "main" ]]; then
            echo "TAGS=ndeepak0x/customkali:stable ndeepak0x/customkali:latest" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == release/* ]]; then
            VERSION=$(echo "$BRANCH_NAME" | cut -d'/' -f2)
            echo "TAGS=ndeepak0x/customkali:v${VERSION}" >> $GITHUB_ENV
          else
            echo "TAGS=ndeepak0x/customkali:dev" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TAGS }}
